### ISSUE TITLE
是否有开源许可？

### ISSUE THREAD

**Issue by lvwzhen** [numbbbbb/Git-Tutorial-By-liaoxuefeng#1]
请问这个教程是否有开源许可？最近也准备做一个gitbook版。谢谢！

**Comment by numbbbbb** [comment]
作者的官网上面没有任何声明，不过我发的那条微博作者本人也转发了，看起来应该是没问题的~

突然发现gitbook很强大啊，作者的原网页应该就是用markdown写的，转换成PDF的话应该比我这个要美观很多。到时候你做好了的话在我这加个链接到你那边吧。

**Comment by lvwzhen** [comment]
已经试着做了几章，最近做好再联系你，先谢谢了。
https://github.com/lvwzhen/Git-Tutorial

**Comment by numbbbbb** [comment]
好~

**Comment by lvwzhen** [comment]
已经做完了初版，谢谢。
http://lvwzhen.github.io/Git-Tutorial/

**Comment by numbbbbb** [comment]
哇，好快！我加上链接
